dist: xenial
matrix:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install -r backend/requirements.txt
        - pip install psycopg2 --quiet
        - pip install codecov
      services:
        - postgresql
      before_script:
        - psql -c "CREATE DATABASE overworld;" -U postgres
      script:
        - python backend/manage.py migrate
        - coverage run backend/manage.py test games actions users
      after_success:
        - codecov
    - language: node_js
      node_js: 
        - "8.10"
      before_script:
        - cd frontend/
        - npm install
        - npm install -g codecov
      script:
        - npm test -- --coverage && codecov
